### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by nmahadkar** [lmm-git/docker-dovecot-solr#1]
I am getting the following error.  Any ideas whats causing this?  Dovecot 2.2.22

`Error: fts_solr: Invalid XML input at 1:0: not well-formed (invalid token) (near: {
|mail          | 2017-10-23T23:17:45.029126423Z Oct 23 23:17:44 vzw dovecot: imap: Error:   "responseHeader":{
|mail          | 2017-10-23T23:17:45.029145636Z Oct 23 23:17:44 vzw dovecot: imap: Error:     "status":0,
|mail          | 2017-10-23T23:17:45.029190088Z Oct 23 23:17:44 vzw dovecot: imap: Error:     "QTime":589,
|mail          | 2017-10-23T23:17:45.029206188Z Oct 23 23:17:44 vzw dovecot: imap: Error:     "params":{
|mail          | 2017-10-23T23:17:45.029221201Z Oct 23 23:17:44 vzw dovecot: imap: Error:       "q":"{!lucene q.op=AND}subject:help OR from:help OR)
`

**Comment by lmm-git** [comment]
Thank you for reporting the issue! Sorry for the delay in fixing it.
